### ISSUE TITLE
Add .NET Core 3.1 Support

### ISSUE THREAD

**Issue by danspark** [RehanSaeed/Serilog.Enrichers.Span#10]
Any reason why .NET Core 3.1 is not supported? I'm trying to find anything specific to .NET 5 but can't seem to find any.

**Comment by RehanSaeed** [comment]
It seems the `Activity` type is not available in `netstandard2.1` but is in `netcoreapp3.1`. I'll take a PR to add support.

**Comment by danspark** [comment]
I'm doing some testing and for some reason SpanId and TraceId are already being added to the properties. I'll see if it's something I added and forgot and if it's the case, I'll open a PR adding a new target framework :)

**Comment by pinkfloydx33** [comment]
Definitely would like this for 3.1 so I can use it in Azure functions. (@danspark I don't get the properties so you must be getting them from elsewhere)

**Comment by danspark** [comment]
Yup, I just confirmed that. I actually had an ActivityListener doing some logic when an Activity stops. I'll be opening a PR soon
