### ISSUE TITLE
Target netstandard2.0

### ISSUE THREAD

**Issue by danspark** [RehanSaeed/Serilog.Enrichers.Span#119]
### Describe the feature

Would love to use this on an existing net461 app, any chance I could open a PR adding it to the targets?

**Comment by RehanSaeed** [comment]
> The .NET Framework versions 4.5.2, 4.6, and 4.6.1 will reach end of support on April 26, 2022.

https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-framework

**Comment by RehanSaeed** [comment]
You can submit a PR.
