### ISSUE TITLE
Make ActivityExtensions public

### ISSUE THREAD

**Issue by oocx** [RehanSaeed/Serilog.Enrichers.Span#137]
### Describe the feature

Hi,

could you please make ActivityExtensions public? We'd like to use GetTraceId() in our code.

We could copy it to our code, but as the package is not that big overall then if we have to copy a part of it, there is not much point in using a package at all and we could just copy everything.

Regards
Mathais

**Comment by RehanSaeed** [comment]
Would accept a small PR.

**Comment by oocx** [comment]
Great, thanks!
