### ISSUE TITLE
ParentSpanId instead of ParentId

### ISSUE THREAD

**Issue by prostakov** [RehanSaeed/Serilog.Enrichers.Span#138]
I'm a bit of newbie in questions of telemetry, but label `ParentId` may seem to be a bit misleading when in actuality it points to SpanId of parent request.

Is there any reason not to log it as `ParentSpanId`? I think it'd give more depth to clarity.

**Comment by RehanSaeed** [comment]
ParentId and ParentSpanId are two different properties on `Activity`. We just use the same names as what .NET uses.

https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.activity

**Comment by prostakov** [comment]
Again, sorry for the stupid question

If we work strictly in W3C format - ParentId will always match ParentSpanId, correct?

**Comment by prostakov** [comment]
I see it
https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.activity.parentspanid?view=net-6.0#system-diagnostics-activity-parentspanid 

OK, issue closed.
