### ISSUE TITLE
Values don't match format of activity values from .NET Core 3.1

### ISSUE THREAD

**Issue by terryaney** [RehanSaeed/Serilog.Enrichers.Span#17]
Version 1.1 of Serilog.Enrichers.Span

Running [this repo](https://github.com/dahlsailrunner/aspnetcore-effective-logging) (to learn more about tracing), the values look like this (site/repo is running on .NET Core 3.1):

```
"SpanId": "|6fda2f3e-488774f9127e4436.",
"TraceId": "6fda2f3e-488774f9127e4436",
"ParentId": ""
```
And when I hit the Error page on error, it uses: `RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;` and displays a value of `|33c532d9-4ddd81ac9fbd7881.` (so it is using the `SpanId`).

Using your package in a .NET 5 Razor Pages site, the values look like this:

```
 "SpanId": "1aff961d5557024f",
 "TraceId": "03689b379c6b734b850c472c86325fac",
 "ParentId": "0000000000000000"
 ```

1. SpanId doesn't have the | and .
2. TraceId looks like a new Guid vs something close to SpanId like .NET Core 3.1 did.
3. ParentId is all 0 instead of just blank.

And when I hit error page in .NET 5 site, the Error page is using same code to assign RequestId but the value is `00-03689b379c6b734b850c472c86325fac-1aff961d5557024f-00` which looks like `00-TraceId-SpanId-00` and it **is** the value of `Activity.Current?.Id`.

TBH, I'm new to .NET Core and am learning so forgive me if wrong understanding, but should these values look more like .NET Core 3.1 values?  Or are you referencing MS code and they simply changed the way you are doing things?

**Comment by RehanSaeed** [comment]
I'm not entirely clear on the differences between .NET Core 3.1 and .NET 5.0.

With .NET Core 3.1 you need to add:

```cs
Activity.DefaultIdFormat = ActivityIdFormat.W3C;
Activity.ForceDefaultIdFormat = true;
```

**Comment by terryaney** [comment]
I just found that out and was coming to comment.  Thanks.
