### ISSUE TITLE
Add option to log TraceState

### ISSUE THREAD

**Issue by mcm-ham** [RehanSaeed/Serilog.Enrichers.Span#173]
### Describe the feature

Similar to Tags and Baggage would be nice to have an option to log Activity.Current.TraceStateString.

**Comment by mcm-ham** [comment]
Happy to create PR for this. I'm thinking of providing config example #67 for new option in readme for this PR.

**Comment by RehanSaeed** [comment]
Out if interest, what do you use this property for? We could take a PR for it.

**Comment by mcm-ham** [comment]
To integrate with an existing system that uses a custom trace id that doesn't conform to traceparent standard. Just following  https://github.com/w3c/baggage/issues/11 that says Correlation-Context (or [baggage](https://www.w3.org/TR/baggage/)) should be kept for user-provided data.
