### ISSUE TITLE
Support transforming trace values

### ISSUE THREAD

**Issue by tshowers-bt** [RehanSaeed/Serilog.Enrichers.Span#240]
### Describe the feature

OTEL and Datadog use different formats for trace and span IDs. If you use OTEL and ship traces to DD via the OTEL collector with its Datadog exporter then it will convert the IDs for you; but then if you ship logs with the OTEL formatted IDs the correlation doesn't work because the values don't match. It would be nice to have a way to specify a transformation to apply to the `Activity` values before they're added to the log event to handle the OTEL -> Datadog conversion or any similarly shaped mismatch.

This is somewhat related to [the field name issue](https://github.com/RehanSaeed/Serilog.Enrichers.Span/issues/28).

Datadog have [docs](https://docs.datadoghq.com/tracing/other_telemetry/connect_logs_and_traces/opentelemetry?tab=net) offering an example of how to convert to their format but it demonstrates adds the converted values to a single log statement so it doesn't scale well across an application let alone to multiple applications. It also references Seriolog directly at the call site of the log statement so it wouldn't play well with the use of Serilog via ILogger nor with logs produced by libraries.

**Comment by tshowers-bt** [comment]
I've been looking at adding a nullable property to `SpanOptions` with a type something like this:

```cs
public interface ITraceFormatConverter
{
    string ConvertTraceId(string traceId);
    string ConvertSpanId(string spanId);
    string ConvertParentId(string parentId);
}
```

My thinking is that it could be added optionally during the logger configuration:

```cs
var configBuilder = new LoggerConfiguration()
    .Enrich.WithSpan(new SpanOptions()
    {
        LogEventPropertiesNames = new()
        {
            TraceId = "dd.trace_id",
            SpanId = "dd.span_id",
        },
        TraceFormatConverter = new OtelToDatadogTraceConverter(),
    })
```

**Comment by tshowers-bt** [comment]
> I've been looking at adding a nullable property to `SpanOptions` with a type something like this:
> 
> ```cs
> public interface ITraceFormatConverter
> {
>     string ConvertTraceId(string traceId);
>     string ConvertSpanId(string spanId);
>     string ConvertParentId(string parentId);
> }
> ```
> 
> My thinking is that it could be added optionally during the logger configuration:
> 
> ```cs
> var configBuilder = new LoggerConfiguration()
>     .Enrich.WithSpan(new SpanOptions()
>     {
>         LogEventPropertiesNames = new()
>         {
>             TraceId = "dd.trace_id",
>             SpanId = "dd.span_id",
>         },
>         TraceFormatConverter = new OtelToDatadogTraceConverter(),
>     })
> ```

I submitted a PR with an option to derive additional properties from the existing trace values rather than modifying them. Modifying the existing properties can be effectively achieved by setting `LogEventPropertiesNames` to match the property names produced by the augmentor. Since this isn't a Datadog library I didn't want the idiosyncrasies of the platform to leak into this feature and this way seemed the least opinionated about what the final result should look like.

**Comment by RehanSaeed** [comment]
This is maybe better supported through use of an existing package:

https://github.com/serilog/serilog-expressions
