### ISSUE TITLE
Allow setting custom values for SpanId, TraceId and ParentId

### ISSUE THREAD

**Issue by evilpilaf** [RehanSaeed/Serilog.Enrichers.Span#28]
Currently the enricher sets properties of `SpanId` `TraceId` and `ParentId` but it'd be great if we can override it to what we want to comply with OTEL and OTLP, e.g. `trace.span_id` `trace.trace_id` `trace.parent_id`

**Comment by RehanSaeed** [comment]
Hey @evilpilaf, do you have more info/links about these names that you'd like to rename them to? Are these part of a standard? Should these be the default?

I get that you want to be able to set the names yourself, just wondering if there is some Open Telemetry standard that we should be conforming to.

**Comment by evilpilaf** [comment]
After a lot of digging because I could not find this info in the official documentation and semantic conventions, I could find that in the `.proto` file for traces we can see these fields https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/trace/v1/trace.proto

**Comment by evilpilaf** [comment]
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/overview.md#semantic-conventions.md

**Comment by RehanSaeed** [comment]
I don't see where `trace.span_id` is defined in that document. After a cursory search, I also couldn't find anything definitive. Would it be worth raising an issue in the Open Telemetry specification repo to determine the naming here?

**Comment by Insomniak47** [comment]
Alternatively just the ability to rename them would also be nice. We're using this enricher but it doesn't really place nicely with datadog and it's correlation. Ideally we'd be able to do it on the dd ingest but that doesn't seem to be working so it'd be nice to override the keys used.

**Comment by RehanSaeed** [comment]
Seems reasonable, would take a PR for it.

**Comment by Insomniak47** [comment]
@RehanSaeed sounds good I'll see if I can work it into our next sprint.

**Comment by diogocp** [comment]
The current names already follow the OpenTelemetry [Log Data Model](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md#trace-context-fields), at least for `TraceId` and `SpanId` (`ParentId` is not specified).

**Comment by RehanSaeed** [comment]
This was released in https://github.com/RehanSaeed/Serilog.Enrichers.Span/releases/tag/2.1.0.
