### ISSUE TITLE
Targetting net standard

### ISSUE THREAD

**Issue by CarlosLanderas** [RehanSaeed/Serilog.Enrichers.Span#33]
Hello. I'm trying to do a shared library to configure different logging sinks with a default configuration and I am using different enrichers:
```xml
<PackageReference Include="Serilog.Enrichers.Process" Version="2.0.1" />
<PackageReference Include="Serilog.Enrichers.Span" Version="1.2.0" />
<PackageReference Include="Serilog.Enrichers.Thread" Version="3.1.0" />
<PackageReference Include="Serilog.Sinks.ApplicationInsights" Version="3.1.0" />
<PackageReference Include="Serilog.Sinks.Console" Version="3.1.1" />
<PackageReference Include="Serilog.Sinks.RollingFile" Version="3.3.0" />
```

The span enricher is the only one not targetting netstandard. Could this be added as a target?

**Comment by RehanSaeed** [comment]
Hi,

Sorry but we use this type which is only available in newer versions:

https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.activity?view=net-5.0
