### ISSUE TITLE
Provide example of setting SpanOptions in appsettings.json

### ISSUE THREAD

**Issue by cdarrigo** [RehanSaeed/Serilog.Enrichers.Span#67]
### Documentation Request - set Enricher options in appsettings

the enricher has a SpanOptions class that allows the user to include span tags in the log events. 
Please provide a sample on how this would be enabled when configuring serilog in appsettings.json file.

**Comment by RehanSaeed** [comment]
Want to submit a PR?

**Comment by benfoster** [comment]
This does not appear to work currently. Tested with the following configuration:

```json
{
  "Serilog": {
    "MinimumLevel": {
      "Default": "Information",
      "Override": {
        "Microsoft": "Warning",
        "Microsoft.AspNetCore": "Warning",
        "System.Net.Http.HttpClient": "Information"
      }
    },
    "Using": ["Serilog.Enrichers.Span"],
    "WriteTo": [
      {
        "Name": "Console"
      }
    ],
    "Enrich": [
      { "Name": "FromLogContext" },
      {
        "Name": "WithSpan",
        "Args": {
          "spanOptions": {
            "IncludeTags": "true"
          }
        }
      }
    ],
    "Properties": {
      "ApplicationName": "test"
    }
  }
}

```

My understanding is that Serilog should automatically bind to the `WithXXX` extension method but doesn't seem to be the case.
