### ISSUE TITLE
Allow to have the operation name from the Activity in span

### ISSUE THREAD

**Issue by Keviento** [RehanSaeed/Serilog.Enrichers.Span#68]
### Describe the feature

The main idea is to be able to have the operation name in the span making it easier to corelate with trace having the same name. 

It could be an option in the SpanOptions like IncludeOperationName.

Let me know if you need further informations !

**Comment by RehanSaeed** [comment]
Want to submit a PR?

**Comment by Azaferany** [comment]
PR  submited on [#192](https://github.com/RehanSaeed/Serilog.Enrichers.Span/pull/192)
