### ISSUE TITLE
Support framework 4.7

### ISSUE THREAD

**Issue by bronumski** [RehanSaeed/Serilog.Enrichers.Span#70]
### Describe the feature

Having to recreate this functionality for a legacy webapi project as I couldn't pull the package in. Not a massive issue but it would be nice to use the tested official package.

**Comment by RehanSaeed** [comment]
Is Span and all API's needed supported there? You can try adding support in a PR and we may just ship it.

**Comment by bronumski** [comment]
I had a quick look and it wasn't as straightforward as adding in the runtime. I will try and get something together for you.

**Comment by bronumski** [comment]
PR created https://github.com/RehanSaeed/Serilog.Enrichers.Span/pull/71

**Comment by RehanSaeed** [comment]
Fixed by https://github.com/RehanSaeed/Serilog.Enrichers.Span/pull/71.
